###### To solve a puzzle, you are given an initial state and a goal state.
###### Target is to reach goal state from initial state using puzzle rules.
######  We can move blank tile only on left, right, up, and down
![Capture.JPG](attachment:Capture.JPG)

# Generate an intial state of NPuzzle

In [1]:
import numpy as np
import random
def get_state(N):
    state = [item for item in range(N*N)]# [0,1,2,...,15]
    random.shuffle(state)
    tmp = np.array(state)
    print(tmp.reshape(N,N))
    return state

In [2]:
get_state(3)

[[7 6 3]
 [2 0 5]
 [1 4 8]]


[7, 6, 3, 2, 0, 5, 1, 4, 8]

# Calculate inversion

Inversion is a pair of tiles that are in the reverse order from where they ought to be. In our case, the bigger number is in front of the smaller one.



![Capture.JPG](attachment:Capture.JPG)

In [3]:
def count_inversion(s):
    count = 0
    for i in range(len(s)):
        for j in range(i+1,len(s)):
            if s[j]!=0 and s[i] > s[j]: count += 1
    return count

In [50]:
s = get_state(4)
print(s)
print(count_inversion(s))

[[ 9  0  4  8]
 [13 10 12 11]
 [ 3  1 14  5]
 [ 2 15  7  6]]
[9, 0, 4, 8, 13, 10, 12, 11, 3, 1, 14, 5, 2, 15, 7, 6]
55


In [ ]:
S  = [9,1,0,2,3]
S.index(0)

2

# **Find blank row**

In [52]:
# find row position of the blank tile
def get_blank_row(s):
    size = int(len(s) ** 0.5)  # Assuming the puzzle is a square grid
    blank_index = s.index(0)    # Assuming 0 represents the blank tile

    # Calculate the row position of the blank tile from the bottom
    row_position = size - (blank_index // size)

    return row_position


In [53]:
    get_blank_row(s)

4

# Solvability Rules

In [ ]:
# apply the rules to decide solvability
#  N, I, R
# define a method to return solvability (input S)
# return True if solvable or False if not

def get_blank_row(s):
    size = int(len(s) ** 0.5)  # Assuming the puzzle is a square grid
    blank_index = s.index(0)    # Assuming 0 represents the blank tile

    # Calculate the row position of the blank tile
    row_position = size - (blank_index // size)

    return row_position



def isSolvable(s):
    N = int(len(s)**0.5)
    I = count_inversion(s)
    R = get_blank_row(s)

    if (N % 2 != 0) and (I % 2 == 0):
        return True
    elif (N % 2 == 0) and (R % 2 != 0) and (I % 2 == 0):
        return True
    elif (N % 2 == 0) and (R % 2 == 0) and (I % 2 != 0):
        return True
    else:
        return False



In [64]:
    S = get_state(4)
    isSolvable(S)


[[ 8  0  2  9]
 [ 3  1 15  7]
 [11  5 12  4]
 [10 14 13  6]]


True